chore: verify the secret is not the issue

diff --git a/.github/workflows/test-netlify-deploy.yaml b/.github/workflows/test-netlify-deploy.yaml
--- a/.github/workflows/test-netlify-deploy.yaml
+++ b/.github/workflows/test-netlify-deploy.yaml
@@ -35,6 +35,17 @@ jobs:
         run: npm ci
 
       - name: Build
+        run: |
+          if [ -z "${{ secrets.NB_GOOGLE_APPS_SCRIPT_URL }}" ]; then
+            echo "::error::SECRET IS EMPTY"
+            exit 1
+          else
+            echo "Secret length: ${#SECRET_VAR}"
+          fi
+        env:
+          SECRET_VAR: ${{ secrets.NB_GOOGLE_APPS_SCRIPT_URL }}
+
+      - name: Compile
         run: npm run build
         env:
           NB_ANALYTICS: true
